### ISSUE TITLE
Consider alternate icon

### ISSUE THREAD

**Issue by aaronchi** [antons/Gitbox-Tweaks#3]
The one you are using right now doesn't really bear much resemblance to the original.

How about this one?
https://dribbble.com/shots/1046732-Gitbox

![gitbox_icon](https://cloud.githubusercontent.com/assets/6336/6235573/4b1959e4-b698-11e4-9a3b-cb3b32e4fcdf.png)

**Comment by antons** [comment]
I dislike the orinal icon, and the icon you mention is a recreation of the original. My intention was to make something different from the original, yet sharing similar themes (blue and green). Something that matches Yosemite better. And the new arrow matches Time Machine, because both Git and Time Machine do version control.
